#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Как узнать объем памяти любого массива (★☆☆)

Чтобы узнать объем памяти любого массива, надо использовать метод nbytes

In [ ]:
print("Объем памяти массива a: ", a.nbytes, "байт")

Объем памяти массива a:  80 байт


#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [ ]:
a4 = np.arange(10, 50)
print(a4)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

Cоздадим обратный вектор с помощью среза

In [ ]:
b = a4[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [ ]:
a6 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(a6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)

In [ ]:
a7 = np.array([1, 2, 0, 0, 4, 0])
nonzero_index = np.nonzero(a7)
print(nonzero_index)

(array([0, 1, 4], dtype=int64),)


ненулевые элементы находятся в индексах 0, 1 и 4 массива a7

#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [ ]:
a8 = np.random.rand(3, 3, 3)
print(a8)

[[[0.76477404 0.63016274 0.75702044]
  [0.91787257 0.66856329 0.6521491 ]
  [0.59979975 0.3474246  0.66603897]]

 [[0.65000001 0.25349976 0.69140209]
  [0.43945253 0.44581004 0.35387226]
  [0.40445066 0.67209808 0.35191501]]

 [[0.3688765  0.08356761 0.75118082]
  [0.20054313 0.30088601 0.41103219]
  [0.18275126 0.11460121 0.00980732]]]


#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [ ]:
a9 = np.random.rand(10, 10)
print(a9)
print('Минимальное значение:', np.min(a9))
print('Максимальное значение:', np.max(a9))

[[0.50193057 0.95236303 0.04741384 0.74803161 0.94483769 0.37073965
  0.32788395 0.18628141 0.94856737 0.28520823]
 [0.92009252 0.35782072 0.06525364 0.44246734 0.66868014 0.21301013
  0.6268259  0.42119388 0.0270576  0.65350903]
 [0.66531135 0.33612325 0.10686473 0.25939865 0.42950761 0.92069259
  0.38099332 0.61392319 0.74409393 0.79033136]
 [0.24226976 0.91123485 0.57846558 0.2587667  0.02150213 0.13379996
  0.21084758 0.40030922 0.45793294 0.51282528]
 [0.81533399 0.2648429  0.18419942 0.62654423 0.26056819 0.39127008
  0.18826857 0.88047434 0.33659363 0.72691754]
 [0.9543442  0.72177136 0.52240942 0.10919047 0.23186305 0.50534239
  0.46424283 0.05999237 0.07709648 0.8575606 ]
 [0.94949105 0.75515736 0.40696762 0.81335151 0.38626845 0.6489745
  0.65405047 0.08281782 0.70520863 0.55349241]
 [0.5531371  0.59944307 0.17634176 0.70258136 0.49161986 0.8855543
  0.00831433 0.50956495 0.88838833 0.14867595]
 [0.5393617  0.90017205 0.25154035 0.23093766 0.81887775 0.8539997
  0.79232041 0.

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [ ]:
a10 = np.random.rand(30)
print(a10)
print('Среднее значение:', np.mean(a10))

[0.9137885  0.50519034 0.80681381 0.69770031 0.2614962  0.90182962
 0.90473754 0.97052855 0.81299041 0.69329672 0.16077645 0.49903386
 0.48338967 0.50000037 0.29645963 0.90195308 0.08282647 0.94656767
 0.61801205 0.96849221 0.38704606 0.23933951 0.85270544 0.0217286
 0.62301888 0.29467311 0.55670696 0.78918789 0.68068657 0.4220889 ]
Среднее значение: 0.5931021787563991


#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)

In [2]:
import numpy as np
ones = np.ones((3,3)).reshape((3,3))
ones[1:-1,1:-1] = 0
ones

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan  # nan

np.nan == np.nan  # False

np.inf > np.nan  # False 

np.nan - np.nan  # nan

np.nan in set([np.nan])  # True 

0.3 == 3 * 0.1  # False

False

#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [3]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [ ]:
# Создаем матрицы
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)

# Умножаем матрицы
C = np.dot(A, B)
print(C)

[[0.34599221 0.74784396]
 [0.39564865 0.61066144]
 [0.33713538 0.36681949]
 [0.37770136 0.89260776]
 [0.44237442 0.8246568 ]]


#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [ ]:
# Создаем одномерный массив со случайными значениями от 1 до 10
arr = np.random.randint(1, 11, 10)
print("Исходный массив:", arr)

# Инвертируем (меняем местами) все элементы, со значениями 3 и 8
mask3 = (arr == 3)
mask8 = (arr == 8)
arr[mask3] = 8
arr[mask8] = 3

print("Массив после инверсии:", arr)

Исходный массив: [ 5  1  6  3  9  9  3  5 10  5]
Массив после инверсии: [ 5  1  6  8  9  9  8  5 10  5]


#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\q10sn1k_\AppData\Local\Temp\ipykernel_21816\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\q10sn1k_\AppData\Local\Temp\ipykernel_21816\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [ ]:
# Создаем два массива
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

# Находим общие значения между массивами
common_values = np.intersect1d(a, b)

# Выводим результат
print(common_values)

[3 4 5]


#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [9]:

A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

A = A.astype(np.float64)
B = B.astype(np.float64)
#поэлементные операции
np.add(A, B, out=A) # A = A + B
np.multiply(A, -0.5, out=A) # A = A * (-1/2)

print(A)

[-3.5 -4.5 -5.5 -6.5 -7.5]


#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [ ]:
# Создаем массив со значениями строк от 0 до 4
a19 = np.arange(5)

# Создаем матрицу 5x5, повторяя массив arr по строкам и столбцам
a19_x_5 = np.tile(a19, (5, 1))

print(a19_x_5)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [4]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [ ]:
# Создаем случайный вектор размера 10
vec = np.random.rand(10)

# Сортируем вектор
sorted_vec = np.sort(vec)

# Выводим результаты
print("Исходный вектор: ", vec)
print("Отсортированный вектор: ", sorted_vec)

Исходный вектор:  [0.75115605 0.40664447 0.35100378 0.2994262  0.79064494 0.90725021
 0.70040972 0.11959257 0.2876442  0.74608251]
Отсортированный вектор:  [0.11959257 0.2876442  0.2994262  0.35100378 0.40664447 0.70040972
 0.74608251 0.75115605 0.79064494 0.90725021]


#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [10]:
arr = np.array([1, 2, 3, 4, 5])

# Суммирование элементов массива с использованием np.add.reduce
sum_result = np.add.reduce(arr)

print(sum_result)

15


#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [ ]:
import numpy as np

# Создаем два случайных массива
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Проверяем, равны ли массивы A и B
if np.array_equal(A, B):
    print("Массивы A и B равны")
else:
    print("Массивы A и B не равны")

Массивы A и B не равны


#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [ ]:
# Создаем случайный вектор размера 10
vector = np.random.rand(10)

# Находим индекс максимального значения
max_idx = np.argmax(vector)

print(vector)

# Заменяем максимальное значение на 0
vector[max_idx] = 0

print(vector)

[0.59877994 0.35276015 0.28923455 0.63516591 0.17854373 0.91112385
 0.43965269 0.38610952 0.51904856 0.88452786]
[0.59877994 0.35276015 0.28923455 0.63516591 0.17854373 0.
 0.43965269 0.38610952 0.51904856 0.88452786]


#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [ ]:
# Int
print('int8: ', np.iinfo(np.int8))
print('int16: ', np.iinfo(np.int16))
print('int32: ', np.iinfo(np.int32))
print('int64: ', np.iinfo(np.int64))

# Unsigned int
print('uint8: ', np.iinfo(np.uint8))
print('uint16: ', np.iinfo(np.uint16))
print('uint32: ', np.iinfo(np.uint32))
print('uint64: ', np.iinfo(np.uint64))

# Float
print('float16: ', np.finfo(np.float16))
print('float32: ', np.finfo(np.float32))
print('float64: ', np.finfo(np.float64))

int8:  Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

int16:  Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

int32:  Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

int64:  Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

uint8:  Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------

uint16:  Machine par

#### 26. Как вывести все значения большого массива? (★★☆)

In [ ]:
import sys

np.set_printoptions(threshold=sys.maxsize)

a = np.random.rand(100, 100)

print(a)

[[2.31354274e-01 2.86940712e-01 7.17058412e-01 1.52636298e-01
  7.23942585e-01 7.34332238e-01 5.09392375e-01 9.34471416e-01
  4.25506455e-01 6.22965630e-01 5.86106436e-01 4.15728330e-01
  8.62297999e-01 9.71236234e-01 3.67197147e-01 8.13890379e-01
  7.57701266e-02 5.79499959e-01 3.50004050e-01 6.47307492e-01
  9.90519262e-01 6.58148780e-01 6.64362556e-01 1.60554214e-02
  1.67071132e-01 1.83488016e-01 5.61542442e-01 8.00877299e-01
  2.21938914e-02 5.10068548e-01 2.72806264e-01 8.31654691e-01
  6.24401632e-01 9.28434878e-01 1.14750742e-01 3.45876390e-01
  1.26902862e-02 4.26325029e-01 2.76330367e-01 8.18116647e-01
  9.84110873e-01 9.72924794e-01 6.15903618e-01 1.56039666e-01
  2.18753543e-01 2.28775097e-01 7.30541958e-01 6.23164050e-02
  4.10522985e-01 7.38043694e-01 3.32430208e-01 5.10779805e-01
  1.44801128e-01 7.69067006e-01 1.96570263e-01 8.79548187e-01
  7.74164530e-01 7.30621563e-01 8.89788892e-01 4.84465918e-02
  1.39247235e-01 3.29079249e-01 5.80994664e-01 9.60296913e-01
  6.1462

#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [ ]:
from scipy.spatial.distance import pdist

a = np.random.rand(100, 2)

distances = pdist(a)

print(distances)

[0.55867615 0.66093382 0.04837465 ... 0.5651246  0.13763238 0.65940003]


#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [ ]:
arr = arr.astype('int32')

#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [15]:
input_string = "1, 2, 3, 4, 5\n6, , , 7, 8\n , , 9, 10, 11"

# Заменяем пропущенные значения на np.nan
input_string = input_string.replace(", ,", ",nan,").replace(", ,", ",nan,")

# Добавляем np.nan для пропущенных значений 
input_string = input_string.replace("\n,", "\n,nan,").replace(",\n", ",nan\n")

# Используйте np.genfromtxt для создания массива
arr = np.genfromtxt(input_string.split("\n"), delimiter=',', dtype=float)

print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [ ]:
A = np.random.rand(5, 3)

print(A)

A_mean = np.mean(A, axis=1)
A_centered = np.subtract(A.T, A_mean).T

print(A_centered)

[[5.83702735e-01 1.17078084e-02 9.37345663e-01]
 [6.80056177e-01 8.91059297e-01 6.38184740e-01]
 [6.26913885e-01 5.83213051e-04 9.42606531e-01]
 [8.21299385e-01 1.93660276e-01 5.81248102e-01]
 [7.35755634e-01 9.40928094e-01 6.61887772e-01]]
[[ 0.072784   -0.49921093  0.42642693]
 [-0.05637723  0.15462589 -0.09824866]
 [ 0.10354601 -0.52278466  0.41923865]
 [ 0.28923013 -0.33840898  0.04917885]
 [-0.0437682   0.16140426 -0.11763606]]


#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

In [ ]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)

print("Исходный вектор a:", a)

print(b)

np.add.at(a, b, 1)

print("Измененный вектор a:", a)

Исходный вектор a: [5 5 9 2 6 4 0 7 9 8]
[2 3 4 8 6 8 2 8 0 5]
Измененный вектор a: [ 6  5 11  3  7  5  1  7 12  8]


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [ ]:
# Создание исходных вектора, массива и списка индексов
X = np.array([1, 2, 3, 4, 5])
F = np.zeros((3, 5))
I = [0, 2, 4]

print("Исходный вектор X:\n", X)
print("Исходный массив F:\n", F)
print("Список индексов I:\n", I)

# Индексация массивов для переноса элементов вектора X в массив F
F[:, I] = X[I]

print("Массив F после переноса элементов вектора X на основе списка индексов I:\n", F)


Исходный вектор X:
 [1 2 3 4 5]
Исходный массив F:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Список индексов I:
 [0, 2, 4]
Массив F после переноса элементов вектора X на основе списка индексов I:
 [[1. 0. 3. 0. 5.]
 [1. 0. 3. 0. 5.]
 [1. 0. 3. 0. 5.]]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [17]:
# Создание четырехмерного массива
arr = np.random.rand(2, 3, 4, 5)

print("Четырехмерный массив:\n", arr)

# Получение суммы по двум последним осям
sum_last_two_axes = np.sum(arr, axis=(-1, -2))

print("Сумма элементов по двум последним осям:\n", sum_last_two_axes)

Четырехмерный массив:
 [[[[0.14589879 0.55740837 0.49109195 0.01590505 0.98322442]
   [0.94449365 0.23516299 0.30067515 0.71556942 0.69135531]
   [0.0046438  0.58961818 0.08663068 0.54756077 0.94428317]
   [0.14525884 0.88290311 0.66048602 0.02350978 0.23067853]]

  [[0.60412017 0.12772387 0.0405627  0.82656694 0.14584408]
   [0.41376737 0.30558318 0.5311068  0.85603203 0.20895321]
   [0.50861667 0.82090241 0.28348417 0.52756133 0.71267262]
   [0.53194753 0.00811913 0.46856067 0.8425702  0.87365006]]

  [[0.45781604 0.34030248 0.70156513 0.42123919 0.56430118]
   [0.85566799 0.04017055 0.32490891 0.5520474  0.62913152]
   [0.98316591 0.80770932 0.14310029 0.38504876 0.74447924]
   [0.63512495 0.97238009 0.64266949 0.85845851 0.96984023]]]


 [[[0.33918729 0.42941739 0.4453669  0.47997351 0.05798605]
   [0.33534573 0.97778512 0.0652593  0.02945657 0.04207376]
   [0.85967571 0.03877368 0.88444972 0.4441718  0.99373675]
   [0.08619016 0.09797418 0.66825314 0.76175132 0.37196467]]

  [[0.1

#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a)

# Создание нового вектора с 3 нулями между каждым элементом
b = np.zeros(len(a) * 4 - 3)
b[::4] = a

print(b)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [ ]:
a = np.random.rand(5, 5, 3)
b = np.random.rand(5, 5)

print("Массив а:\n", a)
print("Массив b:\n", b)

# Умножение двух массивов
c = np.tensordot(a, b, axes=((0, 1), (0, 1)))

print("Массив c:\n", c)

Массив а:
 [[[0.02424689 0.95487676 0.08515635]
  [0.56953868 0.85072473 0.83998416]
  [0.39097812 0.1985958  0.48245511]
  [0.56418818 0.02742724 0.23490194]
  [0.05869812 0.39521829 0.65129009]]

 [[0.39714122 0.09199058 0.37623828]
  [0.10993323 0.58018831 0.12450588]
  [0.3021205  0.91472233 0.40091924]
  [0.39556704 0.86620196 0.29104782]
  [0.85335604 0.76178816 0.39298618]]

 [[0.28249376 0.75167707 0.46174496]
  [0.19530302 0.0208599  0.59047258]
  [0.10416653 0.96411143 0.63568743]
  [0.09350355 0.75838697 0.71889445]
  [0.48363174 0.05544525 0.24759651]]

 [[0.46865633 0.53002658 0.7413265 ]
  [0.09623614 0.58114536 0.77527891]
  [0.30362136 0.70012638 0.11276025]
  [0.85535258 0.97610338 0.37441511]
  [0.93825737 0.82409224 0.68172667]]

 [[0.24883932 0.84736545 0.40471145]
  [0.05901292 0.6863733  0.41773089]
  [0.41762627 0.8791448  0.9453428 ]
  [0.10497486 0.16292178 0.60706046]
  [0.21515857 0.70314578 0.18014436]]]
Массив b:
 [[0.20866678 0.2752023  0.53640085 0.256283

#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [ ]:
x = np.random.rand(100)

print(x)

# Ширина скользящего окна
w = 10

# Вычисляем веса для скользящего окна
weights = np.repeat(1.0, w) / w

# Вычисляем скользящее среднее
# padding='valid' для того, чтобы отбросить некорректные значения на краях
# mode='valid' для того, чтобы вернуть только значения, которые полностью попадают в окно
x_mean = np.convolve(x, weights, mode='valid')

print(x_mean)

[0.92016408 0.95411139 0.99559067 0.83757495 0.40723963 0.55399785
 0.75604727 0.04932763 0.71794223 0.28727212 0.27361639 0.45831235
 0.51025788 0.26038933 0.10646753 0.0668682  0.29175433 0.2054852
 0.73915658 0.3608798  0.85055377 0.89883001 0.89580288 0.57994246
 0.551439   0.72686473 0.89059932 0.53845723 0.27168748 0.61665268
 0.35536407 0.60871809 0.87358598 0.18483827 0.18738828 0.42759686
 0.85295506 0.68720584 0.64424498 0.77300178 0.67743703 0.67953003
 0.64939431 0.66751894 0.29185719 0.63289013 0.38284648 0.59166266
 0.39985284 0.43061371 0.86741776 0.31256295 0.26549177 0.22407449
 0.75928805 0.58086198 0.75582815 0.62070825 0.12651275 0.92636181
 0.60469192 0.88108033 0.67399313 0.09394023 0.78763537 0.11005768
 0.73648885 0.01171105 0.92469929 0.43976947 0.47231119 0.44894827
 0.36430328 0.81694692 0.40760611 0.01592471 0.92062227 0.75383478
 0.33579097 0.68641948 0.15437424 0.29136732 0.81619666 0.47359291
 0.37538721 0.90027599 0.29652062 0.3802024  0.02402156 0.19210

#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [ ]:
# исходный одномерный массив
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(Z)

# длина окна
window_size = 3

# число строк в результирующем двумерном массиве
num_rows = len(Z) - window_size + 1

# создаем подмассивы со смещением в 1 и вертикально объединяем их
result = np.vstack(Z[i:i+window_size] for i in range(num_rows))

print(result)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


C:\Users\q10sn1k_\AppData\Local\Temp\ipykernel_21816\3422911655.py:13: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  result = np.vstack(Z[i:i+window_size] for i in range(num_rows))


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [ ]:
# задаем координаты точек P0, P1 и P
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 1], [2, 2], [3, 3]])
P = np.array([[0, 1], [1, 2], [2, 3]])

print(P0)
print(P1)
print(P)

# вычисляем вектор направления линий
v = P1 - P0

# вычисляем вектора от P0 до P
w = P.reshape((1, P.shape[0], P.shape[1])) - P0.reshape((P0.shape[0], 1, P0.shape[1]))

# вычисляем расстояние
d = np.abs(np.cross(v.reshape((v.shape[0], 1, v.shape[1])), w)) / np.linalg.norm(v, axis=1).reshape((v.shape[0], 1))

print(d)

[[0 0]
 [1 1]
 [2 2]]
[[1 1]
 [2 2]
 [3 3]]
[[0 1]
 [1 2]
 [2 3]]
[[0.70710678 0.70710678 0.70710678]
 [0.70710678 0.70710678 0.70710678]
 [0.70710678 0.70710678 0.70710678]]


#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
n = 4  # число столбцов в R
R = np.lib.stride_tricks.as_strided(Z, shape=(Z.size - n + 1, n), strides=(Z.itemsize, Z.itemsize))
R = R.tolist()
print(R)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


#### 40. Найдите ранг случайной матрицы (★★★)

In [ ]:
A = np.random.rand(3, 5)

print(A)

rank = np.linalg.matrix_rank(A)

print(rank)

[[0.05593207 0.18587478 0.64645687 0.42252452 0.34830995]
 [0.57594836 0.60658949 0.88094711 0.95502509 0.2275412 ]
 [0.33060478 0.71987602 0.73509189 0.25928865 0.88322883]]
3


#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [ ]:
arr = np.random.randint(0, 10, 20)
print(arr)

most_common_value = np.argmax(np.bincount(arr))
print(most_common_value)

[2 8 7 2 5 5 5 4 2 9 6 6 9 6 4 4 6 1 5 4]
4


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [ ]:
A = np.random.randint(0, 5, size=(8, 3))
B = np.random.randint(0, 5, size=(2, 2))
print(A)
print(B)
A_sorted = np.sort(A, axis=1)
B_sorted = np.sort(B, axis=1)

# Поиск строк A, содержащих элементы каждой строки B
result = np.all(np.isin(B_sorted, A_sorted), axis=1)
rows = np.where(result)[0]

print("Массив A:")
print(A)
print("\nМассив B:")
print(B)
print("\nСтроки A, содержащие элементы каждой строки B:")
print(A[rows])

[[0 1 0]
 [4 4 4]
 [3 0 0]
 [4 3 0]
 [0 2 0]
 [3 0 1]
 [0 3 0]
 [2 2 1]]
[[3 3]
 [4 1]]
Массив A:
[[0 1 0]
 [4 4 4]
 [3 0 0]
 [4 3 0]
 [0 2 0]
 [3 0 1]
 [0 3 0]
 [2 2 1]]

Массив B:
[[3 3]
 [4 1]]

Строки A, содержащие элементы каждой строки B:
[[0 1 0]
 [4 4 4]]


#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])

unique_values = np.unique(np.concatenate((a, b)))
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10]
